version: '3'
services:
  graph-node:
    image: graphprotocol/graph-node:latest
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8002:8002'
      - '8030:8030'
      - '8040:8040'
      - '5432:5432'
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'mainnet:http://ethereum:8545'
      GRAPH_LOG: info
    depends_on:
      - ipfs
      - postgres
      - ethereum
    volumes:
      - ./data:/data

  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - '5001:5001'
    volumes:
      - ./ipfs:/data/ipfs

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
    volumes:
      - ./postgres:/var/lib/postgresql/data

  ethereum:
    image: ethereum/client-go:latest
    command: --dev --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api eth,net,web3,debug --ws --ws.addr 0.0.0.0 --ws.port 8546 --ws.origins "*" --ws.api eth,net,web3,debug --mine --miner.threads 1 --allow-insecure-unlock
    ports:
      - '8545:8545'
      - '8546:8546' 